# Copyright (c) JWST Data Analysis. All rights reserved.
# Licensed under the MIT License.

"""Calibration recipe CRUD (``/api/calibration``). Full-mode-only — never
mounted in CE (heavy compute + writes have no place in the read-only CE).

Reads are anonymous-capable but visibility-filtered (seeds and public
recipes for everyone; private recipes only for their owner); writes require
auth. Seed recipes are immutable through the API — they are code-owned.

Wire contract: the envelope fields of a recipe ARE its data — snake_case
step/parameter names inside ``stages`` are meaningful jwst identifiers, so
recipes travel verbatim (no camelCase conversion), mirroring how the jobs
API treats its ``request`` blob.
"""

import uuid

from fastapi import APIRouter, Depends, HTTPException
from pydantic import ValidationError

from app.auth.deps import AuthenticatedUser, optional_user, require_user
from app.calibration.models import CalibrationRecipe
from app.calibration.store import COLLECTION_NAME, RecipeStore
from app.db.client import get_database


router = APIRouter(prefix="/api/calibration", tags=["Calibration"])


def get_recipe_store() -> RecipeStore:
    return RecipeStore(get_database()[COLLECTION_NAME])


def _validate(payload: dict) -> CalibrationRecipe:
    # Bodies arrive as plain dicts (server-controlled fields are injected
    # before validation), so surface pydantic errors as a proper 422.
    try:
        return CalibrationRecipe.model_validate(payload)
    except ValidationError as exc:
        raise HTTPException(
            status_code=422,
            detail=exc.errors(include_url=False, include_context=False),
        ) from exc


def _forbid_seed_mutation(recipe_doc: dict) -> None:
    if recipe_doc.get("source") == "seed":
        raise HTTPException(status_code=403, detail="Seed recipes are immutable")


def _visible_to(recipe: dict, user: AuthenticatedUser | None) -> bool:
    if recipe.get("source") == "seed" or recipe.get("is_public"):
        return True
    if user is None:
        return False
    return recipe.get("created_by") == user.user_id or user.role == "Admin"


@router.get("/recipes")
async def list_recipes(
    user: AuthenticatedUser | None = Depends(optional_user),
    store: RecipeStore = Depends(get_recipe_store),
):
    return {"recipes": await store.list_visible(user.user_id if user else None)}


@router.get("/recipes/{recipe_id}")
async def get_recipe(
    recipe_id: str,
    user: AuthenticatedUser | None = Depends(optional_user),
    store: RecipeStore = Depends(get_recipe_store),
):
    recipe = await store.get(recipe_id)
    # 404 for both "unknown" and "not visible" — don't leak existence.
    if recipe is None or not _visible_to(recipe, user):
        raise HTTPException(status_code=404, detail="Recipe not found")
    return recipe


@router.post("/recipes", status_code=201)
async def create_recipe(
    payload: dict,
    user: AuthenticatedUser = Depends(require_user),
    store: RecipeStore = Depends(get_recipe_store),
):
    payload = dict(payload)
    payload["id"] = f"user-{uuid.uuid4().hex[:12]}"
    payload["source"] = "user"
    payload["created_by"] = user.user_id
    recipe = _validate(payload)
    await store.upsert(recipe)
    return await store.get(recipe.id)


@router.put("/recipes/{recipe_id}")
async def update_recipe(
    recipe_id: str,
    payload: dict,
    user: AuthenticatedUser = Depends(require_user),
    store: RecipeStore = Depends(get_recipe_store),
):
    existing = await store.get(recipe_id)
    if existing is None:
        raise HTTPException(status_code=404, detail="Recipe not found")
    _forbid_seed_mutation(existing)
    if existing.get("created_by") != user.user_id and user.role != "Admin":
        raise HTTPException(status_code=404, detail="Recipe not found")

    payload = dict(payload)
    # Identity/ownership/timestamp fields are server-controlled.
    payload["id"] = recipe_id
    payload["source"] = existing["source"]
    payload["created_by"] = existing["created_by"]
    payload["created_at"] = existing["created_at"]
    payload.pop("updated_at", None)  # regenerated by the model default
    recipe = _validate(payload)
    await store.upsert(recipe)
    return await store.get(recipe_id)


@router.delete("/recipes/{recipe_id}", status_code=204)
async def delete_recipe(
    recipe_id: str,
    user: AuthenticatedUser = Depends(require_user),
    store: RecipeStore = Depends(get_recipe_store),
):
    existing = await store.get(recipe_id)
    if existing is None:
        raise HTTPException(status_code=404, detail="Recipe not found")
    _forbid_seed_mutation(existing)
    if existing.get("created_by") != user.user_id and user.role != "Admin":
        raise HTTPException(status_code=404, detail="Recipe not found")
    await store.delete(recipe_id)
