#!/usr/bin/env bash
# Generate .env files for agent Docker stacks
# Usage: ./scripts/agent-env-init.sh [agent-number]
#
# If no agent number given, generates for all agents.
# Safe to re-run — will not overwrite existing files.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCKER_DIR="$(dirname "$SCRIPT_DIR")/docker"

generate_env() {
    local num="$1"
    local offset=$((num * 10))
    local file="$DOCKER_DIR/.env.agent${num}"

    if [[ -f "$file" ]]; then
        echo "Skipping agent ${num} — $file already exists"
        return
    fi

    cat > "$file" <<ENVEOF
# Agent ${num} - Isolated Docker stack
# Generated by agent-env-init.sh — safe to customize

COMPOSE_CONTAINER_PREFIX=jwst-a${num}

# Ports (offset +${offset} from primary)
FRONTEND_PORT=$((3000 + offset))
BACKEND_PORT=$((5001 + offset))
PROCESSING_PORT=$((8000 + offset))
MONGO_PORT=$((27017 + offset))
DOCS_PORT=$((8001 + offset))

# MongoDB
MONGO_ROOT_USERNAME=admin
MONGO_ROOT_PASSWORD=changeme
MONGO_DATABASE=jwst_data_agent${num}

# Data directory (isolated from primary)
DATA_DIR=../data-agent${num}

# CORS
CORS_ALLOWED_ORIGINS=http://localhost:$((3000 + offset))

# Frontend
VITE_API_URL=http://localhost:$((5001 + offset))

# Processing
MAST_DOWNLOAD_DIR=/app/data/mast
MAST_DOWNLOAD_TIMEOUT=3600
ENVEOF

    echo "Created $file"
}

if [[ $# -ge 1 ]]; then
    generate_env "$1"
else
    generate_env 1
    generate_env 2
fi
