#!/usr/bin/env python3
"""
Interactive Recipe Grader with Version History

Serves a local web UI for reviewing and grading composite images
generated by recipe-walkthrough.py. Supports comparing multiple
versions of the same recipe side by side.

Usage:
    python3 scripts/recipe-grader.py [--port 8888] [--dir data/recipe-review]

Opens http://localhost:8888 in your browser.
Grades are saved to data/recipe-review/grades.json automatically.
"""

import argparse
import json
import re
import sys
import webbrowser
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

DEFAULT_DIR = "data/recipe-review"
DEFAULT_PORT = 8888

# Known preset suffixes to strip from recipe display names
KNOWN_PRESETS = [
    "auto",
    "nasa_press",
    "natural",
    "high_contrast",
    "faint_emission",
    "scientific",
]

VERSION_PATTERN = re.compile(r"^(.+?)(?:\.v(\d{8}(?:[-_]\d+)?))?$")


def parse_image_stem(stem: str) -> tuple[str, str | None, str | None]:
    """Parse an image stem into (recipe_display, preset, version).

    Examples:
        '4-filter_MIRI_nasa_press' → ('4-filter MIRI', 'nasa_press', None)
        '4-filter_MIRI_nasa_press.v20260317' → ('4-filter MIRI', 'nasa_press', '20260317')
    """
    m = VERSION_PATTERN.match(stem)
    base = m.group(1) if m else stem
    version = m.group(2) if m else None

    preset = None
    for p in KNOWN_PRESETS:
        suffix = f"_{p}"
        if base.endswith(suffix):
            preset = p
            base = base[: -len(suffix)]
            break

    recipe = base.replace("_", " ")
    return recipe, preset, version


# ---------------------------------------------------------------------------
# HTML page — single-page app with version history and comparison support
# ---------------------------------------------------------------------------

HTML_PAGE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Recipe Grader — JWST Composites</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #0a0a0f;
    color: #e0e0e0;
    min-height: 100vh;
  }

  /* Header */
  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 12px 24px;
    background: #12121a;
    border-bottom: 1px solid #2a2a3a;
    position: sticky;
    top: 0;
    z-index: 100;
  }
  .header h1 { font-size: 18px; font-weight: 600; color: #7eb8ff; }
  .progress {
    display: flex;
    align-items: center;
    gap: 12px;
    font-size: 14px;
    color: #888;
  }
  .progress-bar {
    width: 200px;
    height: 6px;
    background: #2a2a3a;
    border-radius: 3px;
    overflow: hidden;
  }
  .progress-fill {
    height: 100%;
    background: #4a9eff;
    border-radius: 3px;
    transition: width 0.3s;
  }

  /* Layout */
  .container {
    display: flex;
    height: calc(100vh - 53px);
  }

  /* Sidebar */
  .sidebar {
    width: 280px;
    background: #12121a;
    border-right: 1px solid #2a2a3a;
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
  }
  .filters {
    padding: 12px;
    border-bottom: 1px solid #2a2a3a;
    display: flex;
    gap: 6px;
    flex-wrap: wrap;
  }
  .filter-btn {
    padding: 4px 10px;
    border: 1px solid #3a3a4a;
    border-radius: 12px;
    background: transparent;
    color: #aaa;
    font-size: 12px;
    cursor: pointer;
    transition: all 0.15s;
  }
  .filter-btn:hover { border-color: #5a5a7a; color: #ddd; }
  .filter-btn.active { background: #4a9eff22; border-color: #4a9eff; color: #7eb8ff; }

  .image-list {
    flex: 1;
    overflow-y: auto;
    padding: 8px;
  }
  .image-item {
    padding: 8px 10px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 13px;
    margin-bottom: 2px;
    display: flex;
    align-items: center;
    gap: 8px;
    transition: background 0.1s;
  }
  .image-item:hover { background: #1a1a2a; }
  .image-item.active { background: #1a2a3a; border-left: 2px solid #4a9eff; }
  .image-item .grade-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .grade-dot.ungraded { background: #444; }
  .grade-dot.grade-1 { background: #ff4444; }
  .grade-dot.grade-2 { background: #ff8844; }
  .grade-dot.grade-3 { background: #ffcc44; }
  .grade-dot.grade-4 { background: #88cc44; }
  .grade-dot.grade-5 { background: #44cc88; }
  .image-item .target { color: #888; font-size: 11px; }
  .image-item .recipe { color: #ccc; }
  .version-badge {
    font-size: 10px;
    padding: 1px 6px;
    border-radius: 8px;
    background: #4a9eff22;
    color: #7eb8ff;
    margin-left: auto;
    flex-shrink: 0;
  }
  .grade-delta {
    font-size: 11px;
    margin-left: 4px;
    font-weight: 600;
  }
  .grade-delta.up { color: #44cc88; }
  .grade-delta.down { color: #ff4444; }

  /* Main content */
  .main {
    flex: 1;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  /* Image viewer */
  .viewer {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 16px;
    background: #080810;
    position: relative;
    overflow: hidden;
    gap: 8px;
  }
  .viewer img {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
    border-radius: 4px;
  }
  .viewer .empty {
    color: #555;
    font-size: 16px;
  }
  .image-info {
    position: absolute;
    top: 12px;
    left: 12px;
    background: #000000aa;
    padding: 8px 14px;
    border-radius: 6px;
    font-size: 14px;
    z-index: 10;
  }
  .image-info .target-name { color: #7eb8ff; font-weight: 600; }
  .image-info .recipe-name { color: #aaa; margin-left: 8px; }

  /* Compare mode */
  .viewer.compare-mode {
    display: flex;
    align-items: stretch;
  }
  .compare-pane {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    position: relative;
    min-width: 0;
  }
  .compare-pane img {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
    border-radius: 4px;
  }
  .compare-label {
    position: absolute;
    bottom: 8px;
    left: 50%;
    transform: translateX(-50%);
    background: #000000cc;
    padding: 4px 12px;
    border-radius: 12px;
    font-size: 12px;
    white-space: nowrap;
  }
  .compare-divider {
    width: 2px;
    background: #3a3a4a;
    flex-shrink: 0;
  }

  /* Version strip */
  .version-strip {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 16px;
    background: #0e0e16;
    border-top: 1px solid #2a2a3a;
    border-bottom: 1px solid #2a2a3a;
    overflow-x: auto;
    min-height: 72px;
  }
  .version-strip-label {
    font-size: 11px;
    color: #666;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    flex-shrink: 0;
  }
  .version-thumb {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 6px;
    border: 2px solid transparent;
    transition: all 0.15s;
    flex-shrink: 0;
  }
  .version-thumb:hover { background: #1a1a2a; }
  .version-thumb.active { border-color: #4a9eff; background: #1a2a3a; }
  .version-thumb img {
    width: 48px;
    height: 48px;
    object-fit: cover;
    border-radius: 3px;
  }
  .version-thumb-info {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2px;
  }
  .version-thumb-label {
    font-size: 10px;
    color: #888;
  }
  .version-thumb-grade {
    font-size: 11px;
    font-weight: 600;
  }
  .compare-toggle {
    padding: 4px 12px;
    border: 1px solid #3a3a4a;
    border-radius: 12px;
    background: transparent;
    color: #aaa;
    font-size: 12px;
    cursor: pointer;
    flex-shrink: 0;
    margin-left: auto;
  }
  .compare-toggle:hover { border-color: #5a5a7a; color: #ddd; }
  .compare-toggle.active { background: #4a9eff22; border-color: #4a9eff; color: #7eb8ff; }

  /* Grading panel */
  .grading {
    padding: 16px 24px;
    background: #12121a;
    border-top: 1px solid #2a2a3a;
    display: flex;
    align-items: flex-start;
    gap: 24px;
  }
  .grade-section { display: flex; flex-direction: column; gap: 8px; }
  .grade-section label { font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }

  .stars {
    display: flex;
    gap: 4px;
  }
  .star {
    width: 36px;
    height: 36px;
    border: 2px solid #3a3a4a;
    border-radius: 6px;
    background: transparent;
    color: #666;
    font-size: 18px;
    cursor: pointer;
    transition: all 0.15s;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .star:hover { border-color: #ffcc44; color: #ffcc44; }
  .star.active { background: #ffcc4422; border-color: #ffcc44; color: #ffcc44; }

  .tags {
    display: flex;
    gap: 6px;
    flex-wrap: wrap;
  }
  .tag {
    padding: 5px 12px;
    border: 1px solid #3a3a4a;
    border-radius: 14px;
    background: transparent;
    color: #aaa;
    font-size: 12px;
    cursor: pointer;
    transition: all 0.15s;
  }
  .tag:hover { border-color: #5a5a7a; color: #ddd; }
  .tag.active { background: #4a9eff22; border-color: #4a9eff; color: #7eb8ff; }
  .tag.negative.active { background: #ff444422; border-color: #ff6666; color: #ff8888; }

  .notes-input {
    flex: 1;
    background: #1a1a2a;
    border: 1px solid #3a3a4a;
    border-radius: 6px;
    color: #ddd;
    padding: 8px 12px;
    font-size: 13px;
    font-family: inherit;
    resize: none;
    height: 60px;
  }
  .notes-input:focus { outline: none; border-color: #4a9eff; }

  .nav-buttons {
    display: flex;
    gap: 8px;
    align-self: center;
  }
  .nav-btn {
    padding: 8px 16px;
    border: 1px solid #3a3a4a;
    border-radius: 6px;
    background: transparent;
    color: #ccc;
    font-size: 13px;
    cursor: pointer;
  }
  .nav-btn:hover { background: #1a1a2a; }
  .nav-btn.primary { background: #4a9eff22; border-color: #4a9eff; color: #7eb8ff; }

  kbd {
    display: inline-block;
    padding: 1px 5px;
    font-size: 11px;
    background: #2a2a3a;
    border-radius: 3px;
    color: #888;
    margin-left: 4px;
  }
</style>
</head>
<body>

<div class="header">
  <h1>Recipe Grader</h1>
  <div class="progress">
    <span id="progress-text">0 / 0 graded</span>
    <div class="progress-bar"><div class="progress-fill" id="progress-fill"></div></div>
    <button class="nav-btn" onclick="exportGrades()">Export JSON</button>
    <button class="nav-btn" onclick="exportCSV()">Export CSV</button>
  </div>
</div>

<div class="container">
  <div class="sidebar">
    <div class="filters">
      <button class="filter-btn active" data-filter="all" onclick="setFilter('all')">All</button>
      <button class="filter-btn" data-filter="ungraded" onclick="setFilter('ungraded')">Ungraded</button>
      <button class="filter-btn" data-filter="new" onclick="setFilter('new')">New</button>
      <button class="filter-btn" data-filter="1" onclick="setFilter('1')">1</button>
      <button class="filter-btn" data-filter="2" onclick="setFilter('2')">2</button>
      <button class="filter-btn" data-filter="3" onclick="setFilter('3')">3</button>
      <button class="filter-btn" data-filter="4" onclick="setFilter('4')">4</button>
      <button class="filter-btn" data-filter="5" onclick="setFilter('5')">5</button>
    </div>
    <div class="image-list" id="image-list"></div>
  </div>

  <div class="main">
    <div class="viewer" id="viewer">
      <div class="empty">Select an image from the sidebar</div>
    </div>

    <div id="version-strip-container"></div>

    <div class="grading" id="grading" style="display:none">
      <div class="grade-section">
        <label>Grade <kbd>1-5</kbd></label>
        <div class="stars" id="stars"></div>
      </div>

      <div class="grade-section">
        <label>Issues</label>
        <div class="tags" id="tags"></div>
      </div>

      <div class="grade-section" style="flex:1">
        <label>Notes</label>
        <textarea class="notes-input" id="notes" placeholder="What would improve this?"></textarea>
      </div>

      <div class="nav-buttons">
        <button class="nav-btn" onclick="navigate(-1)">Prev <kbd>A</kbd></button>
        <button class="nav-btn primary" onclick="navigate(1)">Next <kbd>D</kbd></button>
      </div>
    </div>
  </div>
</div>

<script>
const TAG_OPTIONS = [
  { id: 'too_dark', label: 'Too Dark', negative: true },
  { id: 'too_bright', label: 'Too Bright', negative: true },
  { id: 'wrong_colors', label: 'Wrong Colors', negative: true },
  { id: 'noisy', label: 'Noisy', negative: true },
  { id: 'low_detail', label: 'Low Detail', negative: true },
  { id: 'artifacts', label: 'Artifacts', negative: true },
  { id: 'bad_stretch', label: 'Bad Stretch', negative: true },
  { id: 'good_structure', label: 'Good Structure', negative: false },
  { id: 'good_colors', label: 'Good Colors', negative: false },
  { id: 'publication_ready', label: 'Publication Ready', negative: false },
];

let images = [];
let grades = {};
let currentIndex = -1;
let currentFilter = 'all';
let filteredImages = [];
let saveTimeout = null;
let compareMode = false;
let meta = {};  // target/filename → {time_s, size_kb, run_id, ...}

// Version grouping: key → array of image objects sharing the same base
let versionGroups = {};  // "target/baseName" → [{version, filename, ...}, ...]

function formatVersion(v) {
  if (!v) return 'Baseline';
  // Strip sort key (the .0 or .1 between date and preset)
  return v
    .replace(/\.[01]\./, '.')
    .replace(/^00000000\./, 'baseline ')
    .replace(/(\d{4})(\d{2})(\d{2})/, '$1-$2-$3')
    .replace(/[._]/g, ' ');
}

function getVersionGroupKey(img) {
  return img.target + '/' + img.baseName;
}

function getVersionsForImage(img) {
  return versionGroups[getVersionGroupKey(img)] || [img];
}

function buildVersionGroups() {
  versionGroups = {};
  for (const img of images) {
    const key = getVersionGroupKey(img);
    if (!versionGroups[key]) versionGroups[key] = [];
    versionGroups[key].push(img);
  }
  // Sort each group: newest version first, baseline last (left-to-right = new-to-old)
  for (const key of Object.keys(versionGroups)) {
    versionGroups[key].sort((a, b) => {
      if (!a.version) return 1;
      if (!b.version) return -1;
      return b.version.localeCompare(a.version);
    });
  }
}

function getMetaForImage(img) {
  return meta[img.target + '/' + img.filename] || {};
}

function formatTime(s) {
  if (!s && s !== 0) return '';
  return s < 10 ? s.toFixed(1) + 's' : Math.round(s) + 's';
}

async function init() {
  const [imgResp, gradeResp, metaResp] = await Promise.all([
    fetch('/api/images').then(r => r.json()),
    fetch('/api/grades').then(r => r.json()),
    fetch('/api/meta').then(r => r.json()),
  ]);
  images = imgResp;
  grades = gradeResp;
  meta = metaResp;
  buildVersionGroups();

  // Build stars
  const starsEl = document.getElementById('stars');
  for (let i = 1; i <= 5; i++) {
    const btn = document.createElement('button');
    btn.className = 'star';
    btn.textContent = i;
    btn.onclick = () => setGrade(i);
    starsEl.appendChild(btn);
  }

  // Build tags
  const tagsEl = document.getElementById('tags');
  TAG_OPTIONS.forEach(tag => {
    const btn = document.createElement('button');
    btn.className = 'tag' + (tag.negative ? ' negative' : '');
    btn.textContent = tag.label;
    btn.dataset.tagId = tag.id;
    btn.onclick = () => toggleTag(tag.id);
    tagsEl.appendChild(btn);
  });

  applyFilter();
  if (filteredImages.length > 0) selectImage(0);
  updateProgress();
}

function getImageKey(img) {
  return img.target + '/' + img.filename;
}

function getGrade(img) {
  return grades[getImageKey(img)] || {};
}

function applyFilter() {
  if (currentFilter === 'all') {
    filteredImages = [...images];
  } else if (currentFilter === 'ungraded') {
    filteredImages = images.filter(img => !getGrade(img).grade);
  } else if (currentFilter === 'new') {
    // Show only versioned images (not baseline) that have an older version
    filteredImages = images.filter(img => {
      if (!img.version) return false;
      const versions = getVersionsForImage(img);
      return versions.length > 1;
    });
  } else {
    const g = parseInt(currentFilter);
    filteredImages = images.filter(img => getGrade(img).grade === g);
  }
  renderList();
}

function setFilter(f) {
  currentFilter = f;
  document.querySelectorAll('.filter-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.filter === f);
  });
  applyFilter();
  const curKey = currentIndex >= 0 && currentIndex < filteredImages.length
    ? getImageKey(filteredImages[currentIndex]) : null;
  // Keep old selection visible
  if (curKey) {
    const newIdx = filteredImages.findIndex(img => getImageKey(img) === curKey);
    if (newIdx >= 0) { currentIndex = newIdx; highlightActive(); return; }
  }
  if (filteredImages.length > 0) selectImage(0);
}

function renderList() {
  const list = document.getElementById('image-list');
  list.innerHTML = '';
  filteredImages.forEach((img, i) => {
    const g = getGrade(img);
    const versions = getVersionsForImage(img);
    const hasVersions = versions.length > 1;

    // Grade delta: compare to baseline grade
    let deltaHtml = '';
    if (img.version && hasVersions) {
      const baseline = versions.find(v => !v.version) || versions[0];
      const baseGrade = getGrade(baseline).grade;
      const curGrade = g.grade;
      if (curGrade && baseGrade) {
        const diff = curGrade - baseGrade;
        if (diff > 0) deltaHtml = '<span class="grade-delta up">+' + diff + '</span>';
        else if (diff < 0) deltaHtml = '<span class="grade-delta down">' + diff + '</span>';
      }
    }

    const div = document.createElement('div');
    div.className = 'image-item' + (i === currentIndex ? ' active' : '');
    div.innerHTML =
      '<span class="grade-dot ' + (g.grade ? 'grade-' + g.grade : 'ungraded') + '"></span>' +
      '<span>' +
        '<span class="target">' + escapeHtml(img.target) + '</span><br>' +
        '<span class="recipe">' + escapeHtml(img.recipe) +
          (img.version ? ' <span style="color:#666;font-size:11px">' + formatVersion(img.version) + '</span>' : '') +
        '</span>' + deltaHtml +
      '</span>' +
      (hasVersions ? '<span class="version-badge">' + versions.length + 'v</span>' : '');
    div.onclick = () => selectImage(i);
    list.appendChild(div);
  });
}

function escapeHtml(s) {
  const d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}

function highlightActive() {
  document.querySelectorAll('.image-item').forEach((el, i) => {
    el.classList.toggle('active', i === currentIndex);
  });
}

function selectImage(index) {
  if (index < 0 || index >= filteredImages.length) return;
  currentIndex = index;
  compareMode = false;
  renderViewer();
  renderVersionStrip();

  const img = filteredImages[index];
  const g = getGrade(img);

  // Show grading panel
  document.getElementById('grading').style.display = 'flex';

  // Update stars
  document.querySelectorAll('.star').forEach((btn, i) => {
    btn.classList.toggle('active', g.grade && (i + 1) <= g.grade);
  });

  // Update tags
  const activeTags = g.tags || [];
  document.querySelectorAll('.tag').forEach(btn => {
    btn.classList.toggle('active', activeTags.includes(btn.dataset.tagId));
  });

  // Update notes
  document.getElementById('notes').value = g.notes || '';

  highlightActive();
  const activeEl = document.querySelector('.image-item.active');
  if (activeEl) activeEl.scrollIntoView({ block: 'nearest' });
}

function renderViewer() {
  const viewer = document.getElementById('viewer');
  const img = filteredImages[currentIndex];
  if (!img) { viewer.innerHTML = '<div class="empty">Select an image</div>'; return; }

  if (compareMode) {
    const versions = getVersionsForImage(img);
    const current = img;
    // Compare against oldest version; if current IS the oldest, use second-newest
    let baseline = versions[versions.length - 1];
    if (getImageKey(baseline) === getImageKey(current) && versions.length > 1) {
      baseline = versions[versions.length - 2];
    }
    const baseGrade = getGrade(baseline).grade;
    const curGrade = getGrade(current).grade;
    const baseMeta = getMetaForImage(baseline);
    const curMeta = getMetaForImage(current);

    viewer.className = 'viewer compare-mode';
    viewer.innerHTML =
      '<div class="image-info">' +
        '<span class="target-name">' + escapeHtml(img.target) + '</span>' +
        '<span class="recipe-name">' + escapeHtml(img.recipe) + '</span>' +
        '<span style="color:#666; margin-left:8px">' + (currentIndex + 1) + ' / ' + filteredImages.length + '</span>' +
      '</div>' +
      '<div class="compare-pane">' +
        '<img src="/images/' + current.target + '/' + current.filename + '" alt="Current">' +
        '<div class="compare-label">' + formatVersion(current.version) +
          (curGrade ? ' — ' + curGrade + '/5' : '') +
          (curMeta.time_s ? ' — ' + formatTime(curMeta.time_s) : '') + '</div>' +
      '</div>' +
      '<div class="compare-divider"></div>' +
      '<div class="compare-pane">' +
        '<img src="/images/' + baseline.target + '/' + baseline.filename + '" alt="Baseline">' +
        '<div class="compare-label">' + formatVersion(baseline.version) +
          (baseGrade ? ' — ' + baseGrade + '/5' : '') +
          (baseMeta.time_s ? ' — ' + formatTime(baseMeta.time_s) : '') + '</div>' +
      '</div>';
  } else {
    viewer.className = 'viewer';
    viewer.innerHTML =
      '<div class="image-info">' +
        '<span class="target-name">' + escapeHtml(img.target) + '</span>' +
        '<span class="recipe-name">' + escapeHtml(img.recipe) + '</span>' +
        (img.version ? '<span style="color:#666; margin-left:8px">' + formatVersion(img.version) + '</span>' : '') +
        '<span style="color:#666; margin-left:8px">' + (currentIndex + 1) + ' / ' + filteredImages.length + '</span>' +
      '</div>' +
      '<img src="/images/' + img.target + '/' + img.filename + '" alt="' + escapeHtml(img.recipe) + '">';
  }
}

function renderVersionStrip() {
  const container = document.getElementById('version-strip-container');
  const img = filteredImages[currentIndex];
  if (!img) { container.innerHTML = ''; return; }

  const versions = getVersionsForImage(img);
  if (versions.length <= 1) { container.innerHTML = ''; return; }

  const gradeColors = { 1: '#ff4444', 2: '#ff8844', 3: '#ffcc44', 4: '#88cc44', 5: '#44cc88' };

  let html = '<div class="version-strip">';
  html += '<span class="version-strip-label">Versions</span>';

  for (const v of versions) {
    const g = getGrade(v);
    const isActive = getImageKey(v) === getImageKey(img);
    const gradeText = g.grade ? g.grade + '/5' : 'ungraded';
    const gradeColor = g.grade ? gradeColors[g.grade] : '#555';

    const m = getMetaForImage(v);
    const timeText = m.time_s ? formatTime(m.time_s) : '';

    html += '<div class="version-thumb' + (isActive ? ' active' : '') + '" ' +
      'onclick="switchVersion(\'' + v.target + '\', \'' + v.filename + '\')">' +
      '<img src="/images/' + v.target + '/' + v.filename + '" alt="' + formatVersion(v.version) + '">' +
      '<div class="version-thumb-info">' +
        '<span class="version-thumb-label">' + formatVersion(v.version) + '</span>' +
        '<span class="version-thumb-grade" style="color:' + gradeColor + '">' + gradeText + '</span>' +
        (timeText ? '<span class="version-thumb-label">' + timeText + '</span>' : '') +
      '</div>' +
    '</div>';
  }

  html += '<button class="compare-toggle' + (compareMode ? ' active' : '') +
    '" onclick="toggleCompare()">Compare <kbd>C</kbd></button>';
  html += '</div>';

  container.innerHTML = html;
}

function switchVersion(target, filename) {
  const idx = filteredImages.findIndex(
    img => img.target === target && img.filename === filename
  );
  if (idx >= 0) {
    selectImage(idx);
  } else {
    // Version not in current filter — find in full images list and show it
    const img = images.find(i => i.target === target && i.filename === filename);
    if (img) {
      // Temporarily add to filtered list
      filteredImages.push(img);
      selectImage(filteredImages.length - 1);
    }
  }
}

function toggleCompare() {
  const img = filteredImages[currentIndex];
  if (!img) return;
  const versions = getVersionsForImage(img);
  if (versions.length <= 1) return;

  compareMode = !compareMode;
  renderViewer();
  renderVersionStrip();
}

function setGrade(grade) {
  if (currentIndex < 0) return;
  const img = filteredImages[currentIndex];
  const key = getImageKey(img);
  if (!grades[key]) grades[key] = {};
  grades[key].grade = grade;
  saveGrades();
  updateUI();
}

function toggleTag(tagId) {
  if (currentIndex < 0) return;
  const img = filteredImages[currentIndex];
  const key = getImageKey(img);
  if (!grades[key]) grades[key] = {};
  if (!grades[key].tags) grades[key].tags = [];
  const idx = grades[key].tags.indexOf(tagId);
  if (idx >= 0) {
    grades[key].tags.splice(idx, 1);
  } else {
    grades[key].tags.push(tagId);
  }
  saveGrades();
  updateUI();
}

function updateUI() {
  const img = filteredImages[currentIndex];
  const g = getGrade(img);

  document.querySelectorAll('.star').forEach((btn, i) => {
    btn.classList.toggle('active', g.grade && (i + 1) <= g.grade);
  });
  document.querySelectorAll('.tag').forEach(btn => {
    btn.classList.toggle('active', (g.tags || []).includes(btn.dataset.tagId));
  });

  renderList();
  renderVersionStrip();
  updateProgress();
}

function updateProgress() {
  const graded = images.filter(img => getGrade(img).grade).length;
  const total = images.length;
  const pct = total > 0 ? (graded / total * 100) : 0;
  document.getElementById('progress-text').textContent = graded + ' / ' + total + ' graded';
  document.getElementById('progress-fill').style.width = pct + '%';
}

function navigate(delta) {
  selectImage(currentIndex + delta);
}

// Auto-save notes on change (debounced)
document.getElementById('notes').addEventListener('input', (e) => {
  if (currentIndex < 0) return;
  const img = filteredImages[currentIndex];
  const key = getImageKey(img);
  if (!grades[key]) grades[key] = {};
  grades[key].notes = e.target.value;
  clearTimeout(saveTimeout);
  saveTimeout = setTimeout(saveGrades, 500);
});

// Keyboard shortcuts
document.addEventListener('keydown', (e) => {
  if (e.target.tagName === 'TEXTAREA') {
    if (e.key === 'Escape') e.target.blur();
    return;
  }
  if (e.key >= '1' && e.key <= '5') {
    setGrade(parseInt(e.key));
    setTimeout(() => navigate(1), 150);
  }
  if (e.key === 'd' || e.key === 'ArrowRight') navigate(1);
  if (e.key === 'a' || e.key === 'ArrowLeft') navigate(-1);
  if (e.key === 'u') setFilter('ungraded');
  if (e.key === 'n') setFilter('new');
  if (e.key === '0') setFilter('all');
  if (e.key === 'c') toggleCompare();
  if (e.key === 'v') {
    // Cycle through versions
    const img = filteredImages[currentIndex];
    if (!img) return;
    const versions = getVersionsForImage(img);
    if (versions.length <= 1) return;
    const curIdx = versions.findIndex(v => getImageKey(v) === getImageKey(img));
    const nextIdx = (curIdx + 1) % versions.length;
    const next = versions[nextIdx];
    switchVersion(next.target, next.filename);
  }
});

async function saveGrades() {
  await fetch('/api/grades', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(grades),
  });
}

function exportGrades() {
  const blob = new Blob([JSON.stringify(grades, null, 2)], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'recipe-grades.json';
  a.click();
}

function exportCSV() {
  const rows = [['Target', 'Recipe', 'Version', 'Grade', 'Tags', 'Notes', 'GenTime_s', 'Size_KB']];
  images.forEach(img => {
    const g = getGrade(img);
    const m = getMetaForImage(img);
    rows.push([
      img.target,
      img.recipe,
      img.version || 'baseline',
      g.grade || '',
      (g.tags || []).join('; '),
      (g.notes || '').replace(/"/g, '""'),
      m.time_s || '',
      m.size_kb || '',
    ]);
  });
  const csv = rows.map(r => r.map(c => '"' + c + '"').join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'recipe-grades.csv';
  a.click();
}

init();
</script>
</body>
</html>
"""


class GraderHandler(SimpleHTTPRequestHandler):
    """HTTP handler for the grader UI, image serving, and grade persistence."""

    image_dir: Path
    grades_file: Path

    def log_message(self, fmt, *args):
        """Suppress default access logging."""
        pass

    def do_GET(self):
        parsed = urlparse(self.path)

        if parsed.path in ("/", ""):
            self._serve_html()
        elif parsed.path == "/api/images":
            self._serve_image_list()
        elif parsed.path == "/api/grades":
            self._serve_grades()
        elif parsed.path == "/api/meta":
            self._serve_meta()
        elif parsed.path.startswith("/images/"):
            self._serve_image(parsed.path[8:])  # strip /images/
        else:
            self.send_error(404)

    def do_POST(self):
        if self.path == "/api/grades":
            self._save_grades()
        else:
            self.send_error(404)

    def _serve_html(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        self.wfile.write(HTML_PAGE.encode())

    def _serve_image_list(self):
        """Scan image directory and return list with version metadata."""
        result = []
        image_dir = self.__class__.image_dir
        if image_dir.exists():
            for target_dir in sorted(image_dir.iterdir()):
                if not target_dir.is_dir():
                    continue
                target = target_dir.name
                for img_file in sorted(target_dir.glob("*.png")):
                    recipe, preset, version = parse_image_stem(img_file.stem)
                    # baseName = recipe display name (preset-stripped) for grouping.
                    # This groups all presets + versions of the same recipe together
                    # so auto vs nasa_press appear as versions, not separate recipes.
                    base = recipe.replace(" ", "_")
                    # Composite version label for sorting and display.
                    # Format: "run_id.sort_key.preset" where sort_key ensures
                    # auto sorts first (newest-left) in descending order.
                    sort_key = "1" if preset == "auto" else "0"
                    if version and preset:
                        vlabel = f"{version}.{sort_key}.{preset}"
                    elif version:
                        vlabel = version
                    elif preset:
                        vlabel = f"00000000.{sort_key}.{preset}"  # baseline sorts last
                    else:
                        vlabel = None
                    result.append(
                        {
                            "target": target,
                            "recipe": recipe,
                            "filename": img_file.name,
                            "baseName": base,
                            "version": vlabel,
                            "preset": preset,
                        }
                    )

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(result).encode())

    def _serve_grades(self):
        grades_file = self.__class__.grades_file
        grades = {}
        if grades_file.exists():
            grades = json.loads(grades_file.read_text())
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(grades).encode())

    def _serve_meta(self):
        """Serve walkthrough metadata (generation times, sizes)."""
        meta_file = self.__class__.image_dir / "meta.json"
        meta = {}
        if meta_file.exists():
            try:
                meta = json.loads(meta_file.read_text())
            except json.JSONDecodeError:
                pass
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(meta).encode())

    def _save_grades(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)
        grades = json.loads(body)
        grades_file = self.__class__.grades_file
        grades_file.write_text(json.dumps(grades, indent=2))

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"ok":true}')

    def _serve_image(self, rel_path: str):
        image_dir = self.__class__.image_dir
        file_path = image_dir / rel_path
        # Security: ensure path doesn't escape image directory
        try:
            file_path.resolve().relative_to(image_dir.resolve())
        except ValueError:
            self.send_error(403)
            return

        if not file_path.exists():
            self.send_error(404)
            return

        self.send_response(200)
        self.send_header("Content-Type", "image/png")
        self.send_header("Cache-Control", "max-age=3600")
        self.end_headers()
        self.wfile.write(file_path.read_bytes())


def main():
    parser = argparse.ArgumentParser(description="Interactive recipe grading UI")
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"Port (default: {DEFAULT_PORT})",
    )
    parser.add_argument(
        "--dir", default=DEFAULT_DIR, help=f"Image directory (default: {DEFAULT_DIR})"
    )
    parser.add_argument(
        "--no-open", action="store_true", help="Don't auto-open browser"
    )
    args = parser.parse_args()

    image_dir = Path(args.dir).resolve()
    if not image_dir.exists():
        print(f"Image directory not found: {image_dir}")
        sys.exit(1)

    image_count = len(list(image_dir.rglob("*.png")))
    if image_count == 0:
        print(f"No PNG images found in {image_dir}")
        sys.exit(1)

    GraderHandler.image_dir = image_dir
    GraderHandler.grades_file = image_dir / "grades.json"

    server = HTTPServer(("0.0.0.0", args.port), GraderHandler)
    url = f"http://localhost:{args.port}"

    print("Recipe Grader")
    print(f"  Images: {image_count} in {image_dir}")
    print(f"  Grades: {GraderHandler.grades_file}")
    print(f"  URL:    {url}")
    print(
        "\nKeyboard: 1-5 = grade, A/D = prev/next, U = ungraded, N = new, C = compare, V = cycle versions"
    )
    print("Press Ctrl+C to stop.\n")

    if not args.no_open:
        webbrowser.open(url)

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")
        server.server_close()


if __name__ == "__main__":
    main()
