#!/usr/bin/env bash
# server-setup.sh — Bootstrap the JWST app on an EC2 instance
#
# Usage:
#   1. scp this script to the server:
#      scp -i ~/.ssh/jwst-staging.pem scripts/server-setup.sh ec2-user@<IP>:~/
#   2. SSH in and run:
#      ssh -i ~/.ssh/jwst-staging.pem ec2-user@<IP>
#      chmod +x server-setup.sh && ./server-setup.sh
#
# What it does:
#   - Waits for Docker to be ready (from user-data install)
#   - Clones the repo
#   - Creates .env with production values
#   - Builds and starts all services via Docker Compose
#   - Verifies health of all containers
#
# Re-running is safe — it will pull latest code and restart services.

set -euo pipefail

# --- Configuration -----------------------------------------------------------
REPO_URL="https://github.com/Snoww3d/jwst-data-analysis.git"
APP_DIR="$HOME/jwst-app"
BRANCH="main"

# --- Helpers ------------------------------------------------------------------
info()  { printf "\033[1;34m[INFO]\033[0m  %s\n" "$*"; }
ok()    { printf "\033[1;32m[OK]\033[0m    %s\n" "$*"; }
err()   { printf "\033[1;31m[ERROR]\033[0m %s\n" "$*" >&2; }
die()   { err "$@"; exit 1; }

# --- Wait for Docker ----------------------------------------------------------
info "Waiting for Docker to be ready..."
retries=0
while ! docker info &>/dev/null; do
    retries=$((retries + 1))
    if [[ $retries -ge 60 ]]; then
        die "Docker not ready after 5 minutes. Check: sudo systemctl status docker"
    fi
    sleep 5
done
ok "Docker is ready"

# Verify docker compose
docker compose version &>/dev/null || die "Docker Compose plugin not installed"
ok "Docker Compose $(docker compose version --short)"

# --- Clone / Update Repo -----------------------------------------------------
if [[ -d "$APP_DIR/.git" ]]; then
    info "Repo exists — pulling latest changes..."
    cd "$APP_DIR"
    git fetch origin
    git reset --hard "origin/$BRANCH"
    ok "Updated to latest $BRANCH"
else
    info "Cloning repository..."
    git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
    cd "$APP_DIR"
    ok "Cloned to $APP_DIR"
fi

# --- Create data directory ----------------------------------------------------
mkdir -p "$APP_DIR/data/mast"
ok "Data directory ready"

# --- Environment File --------------------------------------------------------
ENV_FILE="$APP_DIR/docker/.env"
if [[ -f "$ENV_FILE" ]]; then
    info ".env already exists — keeping existing values"
else
    info "Creating .env file..."

    # Get the public IP for CORS via EC2 instance metadata
    # Try IMDSv2 first (default on newer instances), fall back to IMDSv1
    TOKEN=$(curl -s --max-time 2 -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60" 2>/dev/null || echo "")
    if [[ -n "$TOKEN" ]]; then
        PUBLIC_IP=$(curl -s --max-time 5 -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "")
    else
        PUBLIC_IP=$(curl -s --max-time 5 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "")
    fi

    if [[ -z "$PUBLIC_IP" ]]; then
        err "Could not detect public IP. You'll need to set CORS_ALLOWED_ORIGINS manually in $ENV_FILE"
        PUBLIC_IP="YOUR_PUBLIC_IP"
    fi

    # Generate a random MongoDB password
    MONGO_PW=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

    cat > "$ENV_FILE" <<EOF
# JWST Staging Environment — generated by server-setup.sh
# To regenerate: delete this file and re-run server-setup.sh

# MongoDB
MONGO_ROOT_USERNAME=admin
MONGO_ROOT_PASSWORD=$MONGO_PW
MONGO_DATABASE=jwst_data_analysis

# Backend
ASPNETCORE_ENVIRONMENT=Production
CORS_ALLOWED_ORIGINS=http://$PUBLIC_IP

# Frontend — in staging, the browser talks to nginx on port 80 which
# proxies /api to the backend. No direct backend URL needed.
VITE_API_URL=

# Processing
MAST_DOWNLOAD_DIR=/app/data/mast
MAST_DOWNLOAD_TIMEOUT=3600

# Storage
STORAGE_PROVIDER=local
EOF

    chmod 600 "$ENV_FILE"
    ok ".env created (MongoDB password auto-generated)"
    info "CORS_ALLOWED_ORIGINS set to http://$PUBLIC_IP"
fi

# --- Build and Start ----------------------------------------------------------
info "Building and starting services (this may take several minutes on first run)..."
cd "$APP_DIR/docker"

docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d --build 2>&1

ok "Services started"

# --- Health Check -------------------------------------------------------------
info "Waiting for services to become healthy..."

check_container() {
    local name="$1"
    local max_wait="${2:-60}"
    local elapsed=0

    while [[ $elapsed -lt $max_wait ]]; do
        local state
        state=$(docker inspect --format='{{.State.Status}}' "$name" 2>/dev/null || echo "missing")
        if [[ "$state" == "running" ]]; then
            return 0
        fi
        sleep 5
        elapsed=$((elapsed + 5))
    done
    return 1
}

all_healthy=true
for service in jwst-mongodb jwst-backend jwst-processing jwst-frontend; do
    if check_container "$service" 120; then
        ok "$service is running"
    else
        err "$service failed to start"
        all_healthy=false
    fi
done

echo ""
if $all_healthy; then
    PUBLIC_IP=$(grep 'CORS_ALLOWED_ORIGINS=' "$ENV_FILE" | sed 's|.*http://||;s|,.*||' 2>/dev/null || echo "<your-ip>")
    echo "========================================"
    echo "  JWST App is running!"
    echo "========================================"
    echo ""
    echo "  URL: http://$PUBLIC_IP"
    echo ""
    echo "  Useful commands:"
    echo "    docker compose -f docker-compose.yml -f docker-compose.staging.yml logs -f"
    echo "    docker compose -f docker-compose.yml -f docker-compose.staging.yml restart"
    echo "    docker compose -f docker-compose.yml -f docker-compose.staging.yml down"
    echo ""
    echo "  To update after pushing new code:"
    echo "    cd $APP_DIR && git pull"
    echo "    cd docker && docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d --build"
    echo "========================================"
else
    echo "Some services failed to start. Check logs:"
    echo "  cd $APP_DIR/docker"
    echo "  docker compose -f docker-compose.yml -f docker-compose.staging.yml logs"
fi
